routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth']], function () {
    Route::resource('place', 'PlaceController');
    //Route::resource('data', 'DataController');
  
    Route::resource('room', 'User\RoomController');
    Route::get('/room-book/{id}', 'User\RoomController@create')->name('room-book');
    Route::get('/service-user', 'User\UserController@service')->name('service-user');
    
    Route::get('/search', 'User\RoomController@search')->name('search');
    Route::get('/type/{id}', 'User\RoomController@type')->name('type');
});

Route::group(['middleware' => ['auth','admin']], function () {
    Route::resource('place', 'PlaceController');
    //Route::resource('data', 'DataController');
    Route::resource('order-admin', 'Admin\OrderController');
    Route::resource('room-admin', 'Admin\RoomController');
    Route::resource('roomtype-admin', 'Admin\RoomtypeController');
 
    Route::get('/confirm-pembayaran', 'Admin\OrderController@confirmPembayaran')->name('confirm-pembayaran');
    Route::get('/checkout-admin', 'Admin\OrderController@checkout')->name('checkout');
    Route::get('/transaction-admin', 'Admin\OrderController@transaction')->name('transaction-admin');
    Route::get('/edit-image-room/{id}', 'Admin\RoomController@editImages')->name('edit-image-room');
    Route::post('/edit-image-room-admin', 'Admin\RoomController@updateImages')->name('edit-image-room-admin');
});

Route::get('/landing', 'User\UserController@index')->name('landing');
Route::get('/', function () {
    return redirect()->route('landing');
});
Route::get('/room-user', 'User\RoomController@index')->name('room-user');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/transaction','TransactionController@index')->name('transaction.index');

app/Http/Controllers/Admin/RoomtypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Roomtype;

class RoomtypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $roomtype=Roomtype::all();
        return view('admin.roomtype.index',compact('roomtype'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type=Roomtype::all();
        return view('admin.roomtype.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'name' => 'required',
            'description' => 'required'
        ]);

        Roomtype::create($request->all());
        return redirect()->route('roomtype-admin.index')->with('pesan', 'data entered successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roomtype = Roomtype::findOrFail($id);
        return view('admin.roomtype.edit',compact('roomtype'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'name' => 'required',
            'description' => 'required'
        ]);

        $room=Roomtype::find($id);
          $room->update($request->all());
        return redirect()->route('roomtype-admin.index')->with('pesan', 'data entered successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $roomtype=Roomtype::find($id);
        $roomtype->delete();
        return redirect()->route('admin.roomtype.index')->with('pesan','data deleted successfully');
    }
}

resources/views/admin/roomtype/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <style type="text/css">
    .card-header {
        background-color: skyblue;
    }
    </style>

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                  <div class="card-header">roomtype</div>
                      <div class="card-body">
                              @include('validate')
                          {!! Form::open(['route'=>'roomtype-admin.store','method'=>'POST']) !!}

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-space-shuttle">roomtype Name</label></i>
                                 <div class="col-md-6">
                                 {!! Form::text('name',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">roomtype Description</label>
                                 <div class="col-md-6">
                                 <textarea name="description" id="" class="form-control"></textarea>
                                 </div>
                           </div>



                               <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-2">
                                        <button type="submit" class="btn btn-success btn-sm">Add data</button>
                                       <a href="{{ route('roomtype-admin.index') }}" class="btn btn-info btn-sm">Back</a>
                                    </div>
                          </div>
                      </div>
                  </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roomtype/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                  <div class="card-header">Edit roomtype</div>
                      <div class="card-body">

                          @include('validate')

                          {!! Form::model($roomtype,['route'=>['roomtype-admin.update',$roomtype->id],'method'=>'PUT']) !!}

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-space-shuttle">roomtype Name</label></i>
                                 <div class="col-md-6">
                                 {!! Form::text('name',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">roomtype Description</label>
                                 <div class="col-md-6">
                                 <textarea name="description" id="" class="form-control">{{$roomtype->description}}</textarea>
                                 </div>
                           </div>

                            <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-2">
                                        <button type="submit" class="btn btn-success btn-sm">Update Data</button>
                                        <a href="{{ route('roomtype-admin.index')  }}" class="btn btn-info btn-sm">Back</a>
                                    </div>
                          </div>
                      </div>
                  </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roomtype/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">roomtype</div>


                   <div class="card-body">
                       <a href="{{ route('roomtype-admin.create') }}" class="btn btn-danger btn-sm">Add roomtype</a>

                      <hr>
                      @include('notification')

                    <table class="table table-bordered" id="users-table">
                       <thead>
                         <tr>
                            <th>No</th>
                            <th>room type Name</th>
                            <th>Edit</th>
                            <th>Delete</th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php $no=1; ?>
                        @foreach ($roomtype as $item)


                        <tr>
                        <td>{{ $no }}</td>
                        <td>{{ $item->name }}</td>
                            <td><a href="{{ route('roomtype-admin.edit',$item->id)}}" class="btn btn-info btn-sm">Edit</a></td>
                            {!! Form::open([ 'route'=>['roomtype-admin.destroy',$item->id], 'method'=>'DELETE']) !!}
                            <td><button type="submit" name="submit" class="btn btn-danger btn-sm">Delete</button></td>
                            {!! Form::close() !!}


                        </tr>
                        <?php $no++; ?>

                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script>
$(function() {
$('#users-table').DataTable();
});
</script>
@endpush