routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth']], function () {
    Route::resource('place', 'PlaceController');
    //Route::resource('data', 'DataController');
  
    Route::resource('room', 'User\RoomController');
    Route::get('/room-book/{id}', 'User\RoomController@create')->name('room-book');
    Route::get('/service-user', 'User\UserController@service')->name('service-user');
    
    Route::get('/search', 'User\RoomController@search')->name('search');
    Route::get('/type/{id}', 'User\RoomController@type')->name('type');
});

Route::group(['middleware' => ['auth','admin']], function () {
    Route::resource('place', 'PlaceController');
    //Route::resource('data', 'DataController');
    Route::resource('order-admin', 'Admin\OrderController');
    Route::resource('room-admin', 'Admin\RoomController');
    Route::resource('roomtype-admin', 'Admin\RoomtypeController');
 
    Route::get('/confirm-pembayaran', 'Admin\OrderController@confirmPembayaran')->name('confirm-pembayaran');
    Route::get('/checkout-admin', 'Admin\OrderController@checkout')->name('checkout');
    Route::get('/transaction-admin', 'Admin\OrderController@transaction')->name('transaction-admin');
    Route::get('/edit-image-room/{id}', 'Admin\RoomController@editImages')->name('edit-image-room');
    Route::post('/edit-image-room-admin', 'Admin\RoomController@updateImages')->name('edit-image-room-admin');
});

Route::get('/landing', 'User\UserController@index')->name('landing');
Route::get('/', function () {
    return redirect()->route('landing');
});
Route::get('/room-user', 'User\RoomController@index')->name('room-user');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/transaction','TransactionController@index')->name('transaction.index');

app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    protected $table = 'room';
    protected $primaryKey = 'id';
    protected $fillable = ['roomtype_id','room_name','room_size','price','jumlah_ruangan','max_orang','facility','description','featured','images'];

    public function order()
    {
        return $this->hasMany('App\Order');
    }

    public function type()
    {
        return $this->belongsTo('App\Roomtype', 'roomtype_id');
    }
}

app/Roomtype.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Roomtype extends Model
{
    protected $table = 'room_type';
    protected $primaryKey = 'id';
    protected $fillable = ['name','description'];

    public function room()
    {
        return $this->hasMany('App\Room');
    }
}

app/Http/Controllers/Admin/RoomController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Room;
use App\Roomtype;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\UploadedFile;

class RoomController extends Controller
{
    
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['room']=Room::all();
        return view('admin.room.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type = Roomtype::all();
        return view('admin.room.create',compact('type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'roomtype_id' => 'required',
            'room_name' => 'required',
            'room_size' => 'required',
            'price' => 'required|numeric',
            'jumlah_ruangan' => 'required|numeric',
            'max_orang' => 'required|numeric',
            'facility' => 'required',
            'description' => 'required',
            'images' => 'mimes:jpeg,jpg,png|max:1000',
        ]);
        
        $file_room = $request->file('images');
        $nama_file_room = time()."_".$file_room->getClientOriginalName();
        $tujuan_upload_room = 'room-images';
        $file_room->move($tujuan_upload_room,$nama_file_room);
        $book = Room::firstorCreate(
            array(
                'roomtype_id' => $request->input('roomtype_id'),
                'room_name' => $request->input('room_name'),
                'room_size' => $request->input('room_size'),
                'price' => $request->input('price'),
                'jumlah_ruangan' => $request->input('jumlah_ruangan'),
                'max_orang' => $request->input('max_orang'),
                'facility' => $request->input('facility'),
                'description' => $request->input('description'),
                'images' => $nama_file_room,
                'featured' => $request->input('featured'),       
            )
        );
        return redirect()->route('room-admin.index')->with('pesan', 'data entered successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $type = Roomtype::all();
        $room = Room::findOrFail($id);
        return view('admin.room.edit',compact('room'),compact('type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'roomtype_id' => 'required',
            'room_name' => 'required',
            'room_size' => 'required',
            'price' => 'required|numeric',
            'jumlah_ruangan' => 'required|numeric',
            'max_orang' => 'required|numeric',
            'facility' => 'required',
            'description' => 'required'
        ]);

        $room=Room::find($id);
        $room->update($request->all());
        return redirect()->route('room-admin.index')->with('pesan', 'data entered successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $room=room::find($id);
        $room->delete();
        return redirect()->route('admin.room.index')->with('pesan','data deleted successfully');
    }

    public function editImages($id)
    {
        $room = Room::findOrFail($id);
        return view('admin.room.editimages',compact('room'));
    }

    public function updateImages(Request $request)
    {
        $room_id = $request->id;
        $request->validate([

            'images' => 'mimes:jpeg,jpg,png|max:1000',
        ]);
        
        $file_room = $request->file('images');
        $nama_file_room = time()."_".$file_room->getClientOriginalName();
        $tujuan_upload_room = 'room-images';
        $file_room->move($tujuan_upload_room,$nama_file_room);

        $image = Room::where('id', '=', $room_id)->update(
            array(
                'images' => $nama_file_room,
                
            )
        );
        return redirect()->route('room-admin.index')->with('pesan', 'data entered successfully');
    }
}

app/Http/Controllers/User/RoomController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Room;
use App\Roomtype;
use App\Order;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $data['room']=Room::all();
        $data['featured']=Room::where('featured',true)->get();
        return view('user.room',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $data['room'] = Room::find($request->id);
        $data['dstart'] = date("Y-m-d");
        $data['dend'] = date('Y-m-d', strtotime("+1 months", strtotime( $data['dstart'])));
        $data['num_days'] = floor((strtotime($data['dend'])-strtotime($data['dstart']))/(60*60*24));
        $data['batas_bayar'] = date('Y-m-d H:i:s', strtotime("+0.5 hours", strtotime( $data['dstart'])));
        $data['jam_sekarang'] = date("Y-m-d H:i:s");
        // $data['order'] = Order::select('checkin','checkout')->get();
        $data['order']  = array();
        $data['sisa']  = array();
        for($i=0; $i<$data['num_days']; $i++){
            $hari = strtotime($data['dstart'] . "+ $i days");
            $cek = Order::where(
                [
                    ['room_id','=',$request->id],
                    ['checkin','<=',date('Y-m-d',$hari)],
                    ['checkout','>=',date('Y-m-d',$hari)],
                ]
            )->get();
            if(count($cek)>0){
                $jml_terpakai = 0;
                foreach ($cek as $key) {
                    $jml_terpakai  =  $jml_terpakai + $key->jumlah_ruangan;
                }
                if($data['room']->jumlah_ruangan == $jml_terpakai){
                    array_push($data['order'],date('Y-m-d',$hari));
                    array_push($data['sisa'],0);
                }
                else{
                    array_push($data['sisa'],$data['room']->jumlah_ruangan-$jml_terpakai);
                }
            }
            else{
                array_push($data['sisa'],$data['room']->jumlah_ruangan);
            }
           
        }
        // dd($data['order']);
        // dd($data['sisa']);
        return view('user.book',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::id();
        $room = $request->id;
        $rooms = Room::find($room);
        $jumlah_orang = $request->input('jumlah_orang');
        $jumlah_ruang = $request->input('jumlah_ruangan');
        $jumlah_maks_orang = $rooms->max_orang * $jumlah_ruang;
        $lama_peminjaman =  $data['num_days'] = floor((strtotime($request->input('checkout'))-strtotime($request->input('checkin')))/(60*60*24));
        $harga = intval($lama_peminjaman+1)*$rooms->price*$jumlah_ruang;
        // dd($harga);
        if($jumlah_maks_orang >= $jumlah_orang && $rooms->jumlah_ruangan >= $jumlah_ruang){
            $book = Order::firstorCreate(
                array(
                    'user_id' => $user,
                    'room_id' => $room,
                    'keperluan' => $request->input('keperluan'),
                    'jumlah_ruangan' => $request->input('jumlah_ruangan'),
                    'jumlah_orang' => $request->input('jumlah_orang'),
                    'checkin' => $request->input('checkin'),
                    'checkout' => $request->input('checkout'),
                    'no_wa' => $request->input('no_wa'),
                    'status_checkout' => false,
                    'status_bayar' => false,
                    'total_harga' => $harga,       
                )
            );
                // dd($request->input());
            return redirect()->route('service-user')->with('pesan', 'data entered successfully');
        }
        else{
            return redirect()->back()->with('pesan', 'maaf jumlah ruang tidak cukup atau jumlah orang terlalu banyak');
        }
        
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
    }
    
    public function search(Request $request)
    {
        $search = $request->input('search');
        $data['room'] = Room::where('room_name','like',"%".$search."%")->orWhere('price','like',"%".$search."%")->get();
        $data['featured'] = Room::where('room_name','like',"%".$search."%")->orWhere('price','like',"%".$search."%")->where('featured',true)->get();
        return view('user.search', $data);
    }

    public function type(Request $request)
    {
        $data['type'] = Roomtype::find($request->id);
        return view('user.type',$data);
    }
}

resources/views/admin/room/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <style type="text/css">
    .card-header {
        background-color: skyblue;
    }
    </style>

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                  <div class="card-header">Room</div>
                      <div class="card-body">
                              @include('validate')
                          {!! Form::open(['route'=>'room-admin.store','method'=>'POST','enctype'=>'multipart/form-data']) !!}
                          <form method="POST" action="{{route('room-admin.store')}}" enctype="multipart/form-data">
                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-space-shuttle">Room Name</label></i>
                                 <div class="col-md-6">
                                 {!! Form::text('room_name',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fab fa-500px">Room Price</label></i>
                                 <div class="col-md-6">
                                 {!! Form::number('price',null,['class'=>'form-control']) !!}
                                 
                                 </div>
                           </div>

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-address-book">Room Type</label></i>
                                 <div class="col-md-6">
                                
                                <select name="roomtype_id" class="form-control" required>
                                @foreach ($type as $item)
                                	<option value="{{$item->id}}">{{ $item->name }}</option>
                                    @endforeach
                                													
								<select>
                                
                                </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-door-closed">Room Amount</label></i>
                                 <div class="col-md-6">
                                    {!! Form::number('jumlah_ruangan',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-door-closed">Max Orang</label></i>
                                 <div class="col-md-6">
                                    {!! Form::number('max_orang',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Room Size</label>
                                 <div class="col-md-6">
                                 {!! Form::text('room_size',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Facility</label>
                                 <div class="col-md-6">
                                 <textarea name="facility" id="" class="form-control"></textarea>
                                 </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Description</label>
                                 <div class="col-md-6">
                                 <textarea name="description" id="" class="form-control"></textarea>
                                 </div>
                           </div>


                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-address-book">Featured</label></i>
                                 <div class="col-md-6">
                                 {!! Form::select('featured',[1=>'Yes',0=>'No'],null,['class'=>'form-control']) !!}
                                </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Images</label>
                                 <div class="col-md-6">
                                 {!! Form::file('images',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-2">
                                    <button type="submit" class="btn btn-success btn-sm">Add data</button>
                                    <a href="{{ route('room-admin.index') }}" class="btn btn-info btn-sm">Back</a>
                                </div>
                            </div>
                        </div>
                  </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/room/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                  <div class="card-header">Edit room</div>
                      <div class="card-body">

                          @include('validate')

                          {!! Form::model($room,['route'=>['room-admin.update',$room->id],'method'=>'PUT']) !!}

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-space-shuttle">Room Name</label></i>
                                 <div class="col-md-6">
                                 {!! Form::text('room_name',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fab fa-500px">Room Price</label></i>
                                 <div class="col-md-6">
                                 {!! Form::number('price',null,['class'=>'form-control']) !!}
                                 
                                 </div>
                           </div>

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-address-book">Room Type</label></i>
                                 <div class="col-md-6">
                                
                                <select name="roomtype_id" class="form-control" required>
                                @foreach ($type as $item)
                                	<option value="{{$item->id}}">{{ $item->name }}</option>
                                    @endforeach
                                													
								<select>
                                
                                </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-door-closed">Room Amount</label></i>
                                 <div class="col-md-6">
                                    {!! Form::number('jumlah_ruangan',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-door-closed">Max Orang</label></i>
                                 <div class="col-md-6">
                                    {!! Form::number('max_orang',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Room Size</label>
                                 <div class="col-md-6">
                                 {!! Form::text('room_size',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Facility</label>
                                 <div class="col-md-6">
                                 <textarea name="facility" id="" class="form-control">{{$room->facility}}</textarea>
                                 </div>
                           </div>

                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Description</label>
                                 <div class="col-md-6">
                                 <textarea name="description" id="" class="form-control">{{$room->description}}</textarea>
                                 </div>
                           </div>


                           <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right"><i class="fas fa-address-book">Featured</label></i>
                                 <div class="col-md-6">
                                 {!! Form::select('featured',[1=>'Yes',0=>'No'],null,['class'=>'form-control']) !!}
                                </div>
                           </div>

                            <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-2">
                                        <button type="submit" class="btn btn-success btn-sm">Update Data</button>
                                        <a href="{{ route('room-admin.index')  }}" class="btn btn-info btn-sm">Back</a>
                                    </div>
                          </div>
                      </div>
                  </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/room/editimages.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                  <div class="card-header">Edit room</div>
                      <div class="card-body">

                          @include('validate')

                          {!! Form::model($room,['route'=>['edit-image-room-admin'],'method'=>'POST','enctype'=>'multipart/form-data']) !!}
                          <input type="hidden" name="id" value="{{$room->id}}">
                          <div class="form-group row">
                            <label class="col-md-2 col-form-label text-md-right">Images</label>
                                 <div class="col-md-6">
                                 {!! Form::file('images',null,['class'=>'form-control']) !!}
                                 </div>
                           </div>
                            <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-2">
                                        <button type="submit" class="btn btn-success btn-sm">Update Data</button>
                                        <a href="{{ route('room-admin.index')  }}" class="btn btn-info btn-sm">Back</a>
                                    </div>
                          </div>
                      </div>
                  </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/room/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">room</div>


                   <div class="card-body">
                       <a href="{{ route('room-admin.create') }}" class="btn btn-danger btn-sm">Add room</a>

                      <hr>
                      @include('notification')

                    <table class="table table-bordered" id="users-table">
                       <thead>
                         <tr>
                            <th>No</th>
                            <th>room Name</th>
                            <th>room Type</th>
                            <th>Edit</th>
                            <th>Delete</th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php $no=1; ?>
                        @foreach ($room as $item)


                        <tr>
                        <td>{{ $no }}</td>
                        <td>{{ $item->room_name }}</td>
                        <td>{{ $item->type->name }}</td>
                            <td><a href="{{ route('room-admin.edit',$item->id)}}" class="btn btn-info btn-sm">Edit Data</a>
                            <a href="{{ route('edit-image-room',$item->id)}}" class="btn btn-info btn-sm">Edit Image</a>
                            </td>
                            {!! Form::open([ 'route'=>['room-admin.destroy',$item->id], 'method'=>'DELETE']) !!}
                            <td><button type="submit" name="submit" class="btn btn-danger btn-sm">Delete</button></td>
                            {!! Form::close() !!}


                        </tr>
                        <?php $no++; ?>

                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('scripts')
<script>
$(function() {
$('#users-table').DataTable();
});
</script>
@endpush