routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth']], function () {
    Route::resource('place', 'PlaceController');
    //Route::resource('data', 'DataController');
  
    Route::resource('room', 'User\RoomController');
    Route::get('/room-book/{id}', 'User\RoomController@create')->name('room-book');
    Route::get('/service-user', 'User\UserController@service')->name('service-user');
    
    Route::get('/search', 'User\RoomController@search')->name('search');
    Route::get('/type/{id}', 'User\RoomController@type')->name('type');
});

Route::group(['middleware' => ['auth','admin']], function () {
    Route::resource('place', 'PlaceController');
    //Route::resource('data', 'DataController');
    Route::resource('order-admin', 'Admin\OrderController');
    Route::resource('room-admin', 'Admin\RoomController');
    Route::resource('roomtype-admin', 'Admin\RoomtypeController');
 
    Route::get('/confirm-pembayaran', 'Admin\OrderController@confirmPembayaran')->name('confirm-pembayaran');
    Route::get('/checkout-admin', 'Admin\OrderController@checkout')->name('checkout');
    Route::get('/transaction-admin', 'Admin\OrderController@transaction')->name('transaction-admin');
    Route::get('/edit-image-room/{id}', 'Admin\RoomController@editImages')->name('edit-image-room');
    Route::post('/edit-image-room-admin', 'Admin\RoomController@updateImages')->name('edit-image-room-admin');
});

Route::get('/landing', 'User\UserController@index')->name('landing');
Route::get('/', function () {
    return redirect()->route('landing');
});
Route::get('/room-user', 'User\RoomController@index')->name('room-user');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/transaction','TransactionController@index')->name('transaction.index');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Sistem Pemesanan Tempat</title>

    <!-- Scripts -->
   <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">

    <link href="{{ asset('css/sticky-footer.css')}}" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <style type="text/css">
    .navbar-expand-md {
        background-color: cornflowerblue;
    }
    </style>
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('images/ceria.png')}}">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <i class="fas fa-assistive-listening-systems"> Sistem Pemesanan Tempat</i>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}"><i class="fas fa-hotel">{{  __('Login')  }} </i></a>
                            </li>
                            <li class="nav-item">

                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}"><i class="fas fa-registered">{{  __('Register')  }}</i></a>
                                @endif
                            </li>
                        @else

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                <i class="fas fa-hotel">Room</i><span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('room-admin.index') }}">
                                    List Room
                                </a>
                                <a class="dropdown-item" href="{{ route('roomtype-admin.index') }}">
                                    Room Type
                                </a>        
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{  route('order-admin.index')  }}"><i class="fas fa-address-card">Order</a></i>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{  route('transaction-admin')  }}"><i class="fas fa-money-bill">Transaction</i></a>
                        </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- jQuery -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- DataTables -->
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    <!-- Bootstrap JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- App scripts -->
    @stack('scripts')
    @yield('chart')
</body>
</html>

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('images/ceria.png')}}">
    <title>Login/Register</title>
    <!-- Custom CSS -->
    <link href="{{asset('adminmart-master/dist/css/style.min.css')}}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        @yield('content')
        
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="{{asset('adminmart-master/assets/libs/jquery/dist/jquery.min.js')}}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{asset('adminmart-master/assets/libs/popper.js/dist/umd/popper.min.js')}}"></script>
    <script src="{{asset('adminmart-master/assets/libs/bootstrap/dist/js/bootstrap.min.js')}}"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
        $(".preloader ").fadeOut();
    </script>
</body>

</html>